"""
Download TinyStories from HuggingFace, train a BPE tokenizer,
and save pre-tokenized binary data for training.

TinyStories is a dataset of short stories generated by GPT-3.5/4,
designed specifically for training small language models (1M-30M params).
Proper grammar, punctuation, and narrative structure.

Runs as part of the Modal image build (or locally with: python prepare_tinystories.py).

Requirements: pip install datasets tokenizers
"""
import os
import json
import array

DATA_DIR = os.environ.get("DATA_DIR", os.path.join(os.path.dirname(__file__), "data"))
NUM_STORIES = int(os.environ.get("NUM_STORIES", "500000"))
VOCAB_SIZE = int(os.environ.get("VOCAB_SIZE", "4096"))


def main():
    os.makedirs(DATA_DIR, exist_ok=True)

    if os.path.exists(os.path.join(DATA_DIR, "train.bin")):
        print("Data already prepared, skipping.")
        return

    from datasets import load_dataset
    from tokenizers import Tokenizer
    from tokenizers.models import BPE
    from tokenizers.trainers import BpeTrainer
    from tokenizers.pre_tokenizers import ByteLevel
    from tokenizers.decoders import ByteLevel as ByteLevelDecoder

    # ── Download stories ─────────────────────────────────────────────
    print(f"Downloading TinyStories (target: {NUM_STORIES} stories)...")
    ds = load_dataset("roneneldan/TinyStories", split="train", streaming=True)

    texts = []
    total_chars = 0
    for row in ds:
        text = (row.get("text") or "").strip()
        if len(text) < 100:
            continue
        texts.append(text)
        total_chars += len(text)
        if len(texts) >= NUM_STORIES:
            break
        if len(texts) % 10000 == 0:
            print(f"  Collected {len(texts)} stories ({total_chars / 1024 / 1024:.1f} MB)")

    print(f"  Total: {len(texts)} stories, {total_chars / 1024 / 1024:.1f} MB")

    # ── Train BPE tokenizer ──────────────────────────────────────────
    print(f"Training BPE tokenizer (vocab_size={VOCAB_SIZE})...")
    tokenizer = Tokenizer(BPE(unk_token=None))
    tokenizer.pre_tokenizer = ByteLevel(add_prefix_space=False, use_regex=True)
    tokenizer.decoder = ByteLevelDecoder()

    trainer = BpeTrainer(
        vocab_size=VOCAB_SIZE,
        special_tokens=["<|endoftext|>"],
        show_progress=True,
        min_frequency=2,
    )
    tokenizer.train_from_iterator(texts, trainer)

    eot_id = tokenizer.token_to_id("<|endoftext|>")
    actual_vocab_size = tokenizer.get_vocab_size()
    print(f"  Vocab size: {actual_vocab_size}, <|endoftext|> ID = {eot_id}")

    tok_path = os.path.join(DATA_DIR, "tokenizer.json")
    tokenizer.save(tok_path)
    print(f"  Saved tokenizer to {tok_path}")

    # ── Encode all stories ───────────────────────────────────────────
    print("Encoding stories...")
    all_tokens = []
    CHUNK = 1000
    for i in range(0, len(texts), CHUNK):
        chunk = texts[i : i + CHUNK]
        outputs = tokenizer.encode_batch(chunk)
        for output in outputs:
            all_tokens.extend(output.ids)
            all_tokens.append(eot_id)
        done = min(i + CHUNK, len(texts))
        if done % 10000 == 0 or done == len(texts):
            print(f"  Encoded {done}/{len(texts)} ({len(all_tokens):,} tokens)")

    print(f"  Total tokens: {len(all_tokens):,}")

    # ── Train / validation split (95 / 5) ────────────────────────────
    split_idx = int(len(all_tokens) * 0.95)
    train_tokens = all_tokens[:split_idx]
    val_tokens = all_tokens[split_idx:]

    for name, data in [("train", train_tokens), ("val", val_tokens)]:
        path = os.path.join(DATA_DIR, f"{name}.bin")
        a = array.array("i", data)
        with open(path, "wb") as f:
            a.tofile(f)
        mb = os.path.getsize(path) / 1024 / 1024
        print(f"  {name}: {len(data):,} tokens ({mb:.1f} MB)")

    # ── Metadata ─────────────────────────────────────────────────────
    meta = {
        "vocab_size": actual_vocab_size,
        "train_tokens": len(train_tokens),
        "val_tokens": len(val_tokens),
        "num_stories": len(texts),
        "eot_token": eot_id,
    }
    meta_path = os.path.join(DATA_DIR, "meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"  Metadata: {json.dumps(meta, indent=2)}")
    print("Done!")


if __name__ == "__main__":
    main()
